import type { Metadata } from "next";
import Providers from "@/components/providers/providers";
import { Roboto } from "next/font/google";

const roboto = Roboto({
  weight: ["300", "400", "500", "700"],
  subsets: ["latin"],
  display: "swap",
  variable: "--font-roboto",
});

export const metadata: Metadata = {
  title: "Create Uzor Next MUI Template",
  description: "Generated by create-uzor-next-mui-template",
};

const RootLayout = ({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) => {
  return (
    <html lang="ru">
      <body className={roboto.variable}>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
};

export default RootLayout;
